datagrid:
    calendar-event-grid:
        source:
            type: orm
            acl_resource: oro_calendar_event_view
            query:
                select:
                    - event.id
                    - CONCAT(CASE WHEN calendar.name IS NOT NULL THEN calendar.name ELSE CONCAT(owner.firstName, ' ',owner.lastName) END, '') AS name
                    - event.title
                    - event.start
                    - event.end
                from:
                    - { table: %oro_calendar.calendar_event.entity.class%, alias: event }
                join:
                    inner:
                        - { join: event.calendar, alias: calendar }
                        - { join: calendar.owner, alias: owner }
                        -
                            join: %oro_calendar.calendar_property.entity.class%
                            alias: connection
                            conditionType: WITH
                            condition: "connection.calendarAlias = 'user' AND connection.calendar = calendar.id AND connection.visible = true"
                        - { join: connection.targetCalendar, alias: targetCalendar }
                where:
                    and:
                        - targetCalendar.owner = @oro_security.security_facade->getLoggedUserId
        columns:
            title:
                label: oro.calendar.calendarevent.title.label
            name:
                label: oro.calendar.calendarevent.calendar.label
            start:
                label: oro.calendar.calendarevent.start.label
                frontend_type: datetime
            end:
                label: oro.calendar.calendarevent.end.label
                frontend_type: datetime
        sorters:
            columns:
                title:
                    data_name: event.title
                name:
                    data_name: name
                start:
                    data_name: event.start
                end:
                    data_name: event.end
            default:
                start: ASC
        filters:
            columns:
                title:
                    type: string
                    data_name: event.title
                name:
                    type: string
                    data_name: name
                start:
                    type: datetime
                    data_name: event.start
                end:
                    type: datetime
                    data_name: event.end
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_calendar_event_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_calendar_event_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_calendarevent
                params:     [ id ]
        actions:
            view:
                type:         navigate
                label:        View
                link:         view_link
                icon:         eye-open
                acl_recource: oro_calendar_event_view
                rowAction:    true
            update:
                type:          navigate
                acl_resource:  oro_calendar_event_create
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_calendar_event_delete
                label:         Delete
                icon:          trash
                link:          delete_link
        options:
            entityHint: calendar_events

    widget-base-calendar-event-grid:
        source:
            type: orm
            acl_resource: oro_calendar_event_view
            query:
                select:
                    - event.id
                    - event.title
                    - event.start
                    - event.end
                from:
                    - { table: %oro_calendar.calendar_event.entity.class%, alias: event }
        columns:
            title:
                label: oro.calendar.calendarevent.title.label
                type: twig
                template: OroCalendarBundle:CalendarEvent:Datagrid/Property/title.html.twig
                frontend_type: html
            start:
                label: oro.calendar.calendarevent.start.label
                frontend_type: datetime
            end:
                label: oro.calendar.calendarevent.end.label
                frontend_type: datetime
        sorters:
            columns:
                title:
                    data_name: event.title
                start:
                    data_name: event.start
                end:
                    data_name: event.end
            default:
                start: ASC
        properties:
            id: ~
        options:
            entityHint: calendar_events

    activity-calendar-event-grid:
        extends: widget-base-calendar-event-grid
        filters:
            columns:
                title:
                    type: string
                    data_name: event.title
                start:
                    type: datetime
                    data_name: event.start
                end:
                    type: datetime
                    data_name: event.end

    users-calendar-select-grid-exclude-owner:
        options:
            entityHint: calendar
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - calendar.id as id
                    - u.username
                    - u.email
                    - u.firstName
                    - u.lastName
                    - u.enabled
                from:
                    - { table: %oro_calendar.calendar.entity.class%, alias: calendar }
                join:
                    inner:
                        - { join: calendar.owner, alias: u }
                where:
                    and:
                        - u.id != @oro_security.security_facade->getLoggedUserId
        columns:
            username:
                label: oro.user.username.label
            email:
                label: oro.user.email.label
            firstName:
                label: oro.user.first_name.label
            lastName:
                label: oro.user.last_name.label
            enabled:
                label: oro.user.enabled.label
                frontend_type: select
                choices:
                   - Inactive
                   - Active

        properties:
            id: ~
        sorters:
            columns:
                username:
                    data_name: u.username
                email:
                    data_name: u.email
                firstName:
                    data_name: u.firstName
                lastName:
                    data_name: u.lastName
                enabled:
                    data_name: u.enabled
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                username:
                    type: string
                    data_name: u.username
                email:
                    type: string
                    data_name: u.email
                firstName:
                    type: string
                    data_name: u.firstName
                lastName:
                    type: string
                    data_name: u.lastName
                enabled:
                    type: choice
                    data_name: u.enabled
                    options:
                        field_options:
                            choices:
                                false: Inactive
                                true:  Active

    base-system-calendar-event-grid:
        source:
            type: orm
            query:
                select:
                    - event.id
                    - calendar.name
                    - event.title
                    - event.start
                    - event.end
                from:
                    - { table: %oro_calendar.calendar_event.entity.class%, alias: event }
                join:
                    inner:
                        - { join: event.systemCalendar, alias: calendar }
                where:
                    and:
                        - calendar.id = :calendarId
            bind_parameters:
                - calendarId
        columns:
            title:
                label: oro.calendar.calendarevent.title.label
            name:
                label: oro.calendar.calendarevent.calendar.label
            start:
                label: oro.calendar.calendarevent.start.label
                frontend_type: datetime
            end:
                label: oro.calendar.calendarevent.end.label
                frontend_type: datetime
        sorters:
            columns:
                title:
                    data_name: event.title
                name:
                    data_name: name
                start:
                    data_name: event.start
                end:
                    data_name: event.end
            default:
                start: ASC
        filters:
            columns:
                title:
                    type: string
                    data_name: event.title
                name:
                    type: string
                    data_name: name
                start:
                    type: datetime
                    data_name: event.start
                end:
                    type: datetime
                    data_name: event.end
        properties:
            id: ~
        options:
            entityHint: calendar_events

    system-calendar-event-grid:
        extends: base-system-calendar-event-grid
        source:
            # @TODO: Add acl_resource: oro_system_calendar_view after BAP-5989 was implemented
            query:
                where:
                    and:
                        - calendar.public = false

    public-system-calendar-event-grid:
        extends: base-system-calendar-event-grid
        options:
            skip_acl_check: true
        source:
            query:
                where:
                    and:
                        - calendar.public = true

    system-calendar-grid:
        source:
            type: orm
            acl_resource: ~
            query:
                select:
                    - sc.id
                    - sc.name as name
                    - o.name as organization
                from:
                    - { table: %oro_calendar.system_calendar.entity.class%, alias: sc }
                join:
                    inner:
                        - { join: sc.organization, alias: o }
        columns:
            name:
                label: oro.calendar.systemcalendar.name.label
            organization:
                label: oro.calendar.systemcalendar.organization.label
        sorters:
            columns:
                name:
                    data_name: name
                organization:
                    data_name: organization
            default:
                name: ASC
        filters:
            columns:
                name:
                    type: string
                    data_name: name
                organization:
                    type: string
                    data_name: organization
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_system_calendar_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_system_calendar_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_systemcalendar
                params:     [ id ]
        actions:
            view:
                type:         navigate
                label:        View
                link:         view_link
                icon:         eye-open
                acl_recource: oro_system_calendar_view
                rowAction:    true
            update:
                type:          navigate
                acl_resource:  oro_system_calendar_create
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_system_calendar_delete
                label:         Delete
                icon:          trash
                link:          delete_link
        options:
            skip_acl_check: true
