datagrid:
    widget-base-calendar-event-grid:
        source:
            type: orm
            acl_resource: oro_calendar_event_view
            query:
                select:
                    - event.id
                    - event.title
                    - event.start
                    - event.end
                from:
                    - { table: %oro_calendar.calendar_event.entity.class%, alias: event }
                join:
                    inner:
                        - { join: event.calendar, alias: calendar }
                where:
                    and:
                      - calendar.owner = @oro_security.security_facade->getLoggedUserId
        columns:
            title:
                label: oro.calendar.calendarevent.title.label
                type: twig
                template: OroCalendarBundle:CalendarEvent:Datagrid/Property/title.html.twig
                frontend_type: html
            start:
                label: oro.calendar.calendarevent.start.label
                frontend_type: datetime
            end:
                label: oro.calendar.calendarevent.end.label
                frontend_type: datetime
        sorters:
            columns:
                title:
                    data_name: call.title
                start:
                    data_name: event.start
                end:
                    data_name: event.end
            default:
                start: ASC
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_calendar_event_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_calendar_event_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_calendarevent
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_calendar_event_view
                label:         oro.grid.action.view
                icon:          eye-open
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_calendar_event_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_calendar_event_delete
                label:         oro.grid.action.delete
                icon:          trash
                link:          delete_link
        options:
            entityHint: calendar_events

    activity-calendar-event-grid:
        extends: widget-base-calendar-event-grid
        filters:
            columns:
                title:
                    type: string
                    data_name: event.title
                start:
                    type: datetime
                    data_name: event.start
                end:
                    type: datetime
                    data_name: event.end
