datagrid:
    calendar-event-grid:
        source:
            type: orm
            acl_resource: oro_calendar_event_view
            query:
                select:
                    - event.id
                    - CONCAT(CASE WHEN calendar.name IS NOT NULL THEN calendar.name ELSE CONCAT(owner.firstName, ' ',owner.lastName) END, '') AS name
                    - event.title
                    - event.start
                    - event.end
                    - event.invitationStatus
                    - parent.id as parentId
                    - owner.id as ownerId
                from:
                    - { table: %oro_calendar.calendar_event.entity.class%, alias: event }
                join:
                    left:
                        - { join: event.parent, alias: parent }
                    inner:
                        - { join: event.calendar, alias: calendar }
                        - { join: calendar.owner, alias: owner }
                        -
                            join: %oro_calendar.calendar_property.entity.class%
                            alias: connection
                            conditionType: WITH
                            condition: "connection.calendarAlias = 'user' AND connection.calendar = calendar.id AND connection.visible = true"
                        - { join: connection.targetCalendar, alias: targetCalendar }
                where:
                    and:
                        - targetCalendar.owner = @oro_security.security_facade->getLoggedUserId
        columns:
            title:
                label: oro.calendar.calendarevent.title.label
            name:
                label: oro.calendar.calendarevent.calendar.label
            start:
                label: oro.calendar.calendarevent.start.label
                frontend_type: datetime
            end:
                label: oro.calendar.calendarevent.end.label
                frontend_type: datetime
            invitationStatus:
                label: oro.calendar.calendarevent.invitationStatus.label
                type: twig
                template: OroCalendarBundle:CalendarEvent:Datagrid/Property/status.html.twig
                frontend_type: html
        sorters:
            columns:
                title:
                    data_name: event.title
                name:
                    data_name: name
                start:
                    data_name: event.start
                end:
                    data_name: event.end
                invitationStatus:
                    data_name: event.invitationStatus
            default:
                start: ASC
        filters:
            columns:
                title:
                    type: string
                    data_name: event.title
                name:
                    type: string
                    data_name: name
                start:
                    type: datetime
                    data_name: event.start
                end:
                    type: datetime
                    data_name: event.end
                invitationStatus:
                    type: choice
                    data_name: event.invitationStatus
                    options:
                        field_options:
                            choices:
                                not_responded: oro.calendar.calendarevent.statuses.not_responded
                                accepted: oro.calendar.calendarevent.statuses.accepted
                                tentatively_accepted: oro.calendar.calendarevent.statuses.tentatively_accepted
                                declined: oro.calendar.calendarevent.statuses.declined
        properties:
            id: ~
            view_link:
                type:       url
                route:      oro_calendar_event_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_calendar_event_update
                params:     [ id ]
            delete_link:
                type:       url
                route:      oro_api_delete_calendarevent
                params:     [ id ]
            accept_link:
                type:       url
                route:      oro_calendar_event_accepted
                params:     [ id ]
            tentatively_link:
                type:       url
                route:      oro_calendar_event_tentatively_accepted
                params:     [ id ]
            decline_link:
                type:       url
                route:      oro_calendar_event_declined
                params:     [ id ]
        actions:
            accept:
                type:         ajax
                label:        Accept
                link:         accept_link
                icon:         ok
                acl_recource: oro_calendar_event_view
            tentatively:
                type:         ajax
                label:        Tentative
                link:         tentatively_link
                icon:         question
                acl_recource: oro_calendar_event_view
            decline:
                type:         ajax
                label:        Decline
                link:         decline_link
                icon:         remove
                acl_recource: oro_calendar_event_view
            view:
                type:         navigate
                label:        View
                link:         view_link
                icon:         eye-open
                acl_recource: oro_calendar_event_view
                rowAction:    true
            update:
                type:          navigate
                acl_resource:  oro_calendar_event_create
                label:         Update
                icon:          edit
                link:          update_link
            delete:
                type:          delete
                acl_resource:  oro_calendar_event_delete
                label:         Delete
                icon:          trash
                link:          delete_link
        action_configuration: [@oro_calendar.datagrid.action_permission_provider, "getInvitationPermissions"]
        options:
            entityHint: calendar_events

    widget-base-calendar-event-grid:
        source:
            type: orm
            acl_resource: oro_calendar_event_view
            query:
                select:
                    - event.id
                    - event.title
                    - event.start
                    - event.end
                from:
                    - { table: %oro_calendar.calendar_event.entity.class%, alias: event }
        columns:
            title:
                label: oro.calendar.calendarevent.title.label
                type: twig
                template: OroCalendarBundle:CalendarEvent:Datagrid/Property/title.html.twig
                frontend_type: html
            start:
                label: oro.calendar.calendarevent.start.label
                frontend_type: datetime
            end:
                label: oro.calendar.calendarevent.end.label
                frontend_type: datetime
        sorters:
            columns:
                title:
                    data_name: event.title
                start:
                    data_name: event.start
                end:
                    data_name: event.end
            default:
                start: ASC
        properties:
            id: ~
        options:
            entityHint: calendar_events

    activity-calendar-event-grid:
        extends: widget-base-calendar-event-grid
        filters:
            columns:
                title:
                    type: string
                    data_name: event.title
                start:
                    type: datetime
                    data_name: event.start
                end:
                    type: datetime
                    data_name: event.end

    users-calendar-select-grid-exclude-owner:
        options:
            entityHint: calendar
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - calendar.id as id
                    - u.username
                    - u.email
                    - u.firstName
                    - u.lastName
                    - u.enabled
                from:
                    - { table: %oro_calendar.calendar.entity.class%, alias: calendar }
                join:
                    inner:
                        - { join: calendar.owner, alias: u }
                where:
                    and:
                        - u.id != @oro_security.security_facade->getLoggedUserId
        columns:
            username:
                label: oro.user.username.label
            email:
                label: oro.user.email.label
            firstName:
                label: oro.user.first_name.label
            lastName:
                label: oro.user.last_name.label
            enabled:
                label: oro.user.enabled.label
                frontend_type: select
                choices:
                   - Inactive
                   - Active

        properties:
            id: ~
        sorters:
            columns:
                username:
                    data_name: u.username
                email:
                    data_name: u.email
                firstName:
                    data_name: u.firstName
                lastName:
                    data_name: u.lastName
                enabled:
                    data_name: u.enabled
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC
        filters:
            columns:
                username:
                    type: string
                    data_name: u.username
                email:
                    type: string
                    data_name: u.email
                firstName:
                    type: string
                    data_name: u.firstName
                lastName:
                    type: string
                    data_name: u.lastName
                enabled:
                    type: choice
                    data_name: u.enabled
                    options:
                        field_options:
                            choices:
                                false: Inactive
                                true:  Active
