oro_menu_config:
    items:
        oro_calendar_default:
            label: 'Calendar'
            route: 'oro_calendar_view_default'
    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        oro_calendar_default: ~

oro_titles:
    oro_calendar_default: "%%username%% - Calendar"
    oro_calendar_view: "%%username%% - Calendar"
