oro_menu_config:
    templates:
        calendar_menu:
            template: 'OroCalendarBundle:Calendar:Menu/contextMenu.html.twig'
            rootClass: 'dropdown-menu context-menu'
    items:
        oro_calendar_view_default:
            label: 'oro.calendar.menu.view_default'
            route: 'oro_calendar_view_default'
            extras:
                position: 20
        oro_calendar_hide_action:
            label: 'oro.calendar.context.remove'
            uri: '#'
            extras:
                position: 20
                module: 'orocalendar/js/calendar/menu/hide-calendar-action'
                template: 'OroCalendarBundle:Calendar:Menu/hideCalendar.html.twig'
        oro_calendar_visible_action:
            uri: '#'
            extras:
                position: 10
                module: 'orocalendar/js/calendar/menu/visible-calendar-action'
                template: 'OroCalendarBundle:Calendar:Menu/visibleCalendar.html.twig'
        calendar_event_list:
            label: 'oro.calendar.calendarevent.entity_plural_label'
            route: 'oro_calendar_event_index'
            extras:
                position: 50
                routes: ['oro_calendar_event_*']

    tree:
        application_menu:
            children:
                activities_tab:
                    children:
                        calendar_event_list: ~
        usermenu:
            children:
                oro_calendar_view_default: ~

        calendar_menu:
            type: calendar_menu
            children:
                oro_calendar_hide_action: ~
                oro_calendar_visible_action: ~

oro_titles:
    oro_calendar_view_default: "My Calendar - %%username%%"
    oro_calendar_view: "%%calendarname%% - Calendars - %%username%%"
    oro_calendar_event_index: ~
    oro_calendar_event_view: '%%entity.title%%'
    oro_calendar_event_create: oro.ui.create_entity
    oro_calendar_event_update: '%%entity.title%% - Edit'
