placeholders:
    oro_reminder_reminder_templates:
        items:
            calendar_event_reminder_template: ~
items:
    calendar_event_reminder_template:
        template: OroCalendarBundle:CalendarEvent:reminderTemplate.html.twig

    oro_add_calendar_event_button:
        template: OroCalendarBundle:CalendarEvent:activityButton.html.twig
        acl: oro_calendar_event_create
        data:
            label: @oro_calendar.label_provider.action_button->getLabel($entity$)
            widget_title: @oro_calendar.label_provider.action_button->getWidgetTitle($entity$)

    oro_add_calendar_event_link:
        template: OroCalendarBundle:CalendarEvent:activityLink.html.twig
        acl: oro_calendar_event_create
        data:
            label: @oro_calendar.label_provider.action_button->getLabel($entity$)
            widget_title: @oro_calendar.label_provider.action_button->getWidgetTitle($entity$)
