config:
    shim:
        'jquery.fullcalendar':
            deps:
                - 'jquery'
                - 'jquery-ui'
        'oro/calendar':
            deps:
                - 'jquery.fullcalendar'
    paths:
        'jquery.fullcalendar': 'orocalendar/lib/fullcalendar/fullcalendar'
        'oro/calendar': 'orocalendar/js/calendar/calendar'
        'oro/calendar/connection-collection': 'orocalendar/js/calendar/connection-collection'
        'oro/calendar/connection-model': 'orocalendar/js/calendar/connection-model'
        'oro/calendar/connection-view': 'orocalendar/js/calendar/connection-view'
        'oro/calendar/event-collection': 'orocalendar/js/calendar/event-collection'
        'oro/calendar/event-model': 'orocalendar/js/calendar/event-model'
        'oro/calendar/event-view': 'orocalendar/js/calendar/event-view'
