oro_system_configuration:
    groups:
        calendar_settings:
            title:       oro.calendar.system_configuration.groups.calendar_settings.title

    fields:
        oro_calendar.calendar_colors:
            data_type: array
            type: oro_color_table
            options:
                label: oro.calendar.system_configuration.fields.calendar_colors.label
                module: oroconfig/js/app/components/color-table
        oro_calendar.event_colors:
            data_type: array
            type: oro_color_table
            options:
                label: oro.calendar.system_configuration.fields.event_colors.label
                module: oroconfig/js/app/components/color-table

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                children:
                                    calendar_settings:
                                        children:
                                            - oro_calendar.calendar_colors
                                            - oro_calendar.event_colors

    api_tree:
        outlook:
            contacts:
                oro_calendar.calendar_colors: ~
                oro_calendar.event_colors: ~
