Oro\Bundle\CalendarBundle\Entity\CalendarEvent:
    properties:
        title:
            - NotBlank:     ~
            - Length:
                max: 255
        start:
            - DateTime:     ~
            - NotBlank:     ~
            - Oro\Bundle\CalendarBundle\Validator\Constraints\DateEarlierThan: end
        end:
            - DateTime:     ~
            - NotBlank:     ~

Oro\Bundle\CalendarBundle\Entity\CalendarProperty:
    properties:
        targetCalendar:
            - NotBlank:     ~
        calendarAlias:
            - NotBlank:     ~
            - Length:
                max: 32
        calendar:
            - NotBlank:     ~
        color:
            - Length:
                max: 6
        backgroundColor:
            - Length:
                max: 6
