Oro\Bundle\CalendarBundle\Entity\CalendarEvent:
    properties:
        title:
            - NotBlank:     ~
            - Length:
                max: 255
        start:
            - DateTime:     ~
            - NotBlank:     ~
            - Oro\Bundle\CalendarBundle\Validator\Constraints\DateEarlierThan: end
        end:
            - DateTime:     ~
            - NotBlank:     ~
