Oro\Bundle\CalendarBundle\Entity\CalendarEvent:
    properties:
        title:
            - NotBlank:     ~
        start:
            - Date:         ~
            - NotBlank:     ~
            - Oro\Bundle\CalendarBundle\Validator\Constraints\DateEarlierThan: end
        end:
            - Date:         ~
            - NotBlank:     ~
